/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { useForm } from "react-hook-form";
import { api } from "~/utils/api";

type addFriendForm = {
  userId: string;
};

const AddFriend: NextPage = () => {
  const router = useRouter();
  const addFriend = api.messRouter.addFriend.useMutation();
  const user = useUser();

  const { register, handleSubmit } = useForm<addFriendForm>();
  const onSubmit = async (formData: addFriendForm) => {
    await addFriend
      .mutateAsync({
        userId: formData.userId,
      })
      .then(async () => {
        await router.push("/");
      });
  };

  return (
    <>
      <Head>
        <title>MessMe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ml-64 flex min-h-screen flex-col items-center justify-center bg-gray-900 py-2">
        <h1 className="text-6xl font-bold">Add new Friend</h1>
        <h2>
          <button
            className="text-2xl font-bold text-red-400"
            onClick={
              /* copy to clipboard username */
              async () => {
                await navigator.clipboard.writeText(user.user?.id as string);
              }
            }
          >
            Copy your ID
          </button>
        </h2>
        <div className="flex flex-col justify-center py-2">
          <form
            className="flex w-full flex-row items-center justify-center"
            onSubmit={handleSubmit(onSubmit)}
          >
            <input
              {...register("userId", { required: true })}
              type="text"
              placeholder="Search"
              className="h-10 rounded-lg border-2 border-gray-300 bg-gray-800 px-5 pr-16 text-sm focus:outline-none"
            />
            <button
              type="submit"
              className="ml-4 rounded border-2 border-red-400"
            >
              {/* svg arrow to right in box */}
              <svg
                className="h-6 w-6 text-white"
                aria-hidden="true"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M13.707 10l-3.853 3.853a1 1 0 11-1.414-1.414L10.586 10 8.44 7.854a1 1 0 111.414-1.414L13.707 10z"></path>
              </svg>
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default AddFriend;
