import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const ChatsId: NextPage = () => {
  const router = useRouter();
  const id = router.query.id as string;

  return (
    <>
      <Head>
        <title>MessMe Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ml-64 flex min-h-screen flex-col justify-center py-2">
        <h1 className="text-6xl font-bold">
          Chat
          <span className="text-red-400">{id}</span>
        </h1>
      </div>
    </>
  );
};

export default ChatsId;
