import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Chats: NextPage = () => {
  const friends = api.messRouter.getUsers.useQuery();

  return (
    <>
      <Head>
        <title>MessMe Chats</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ml-64 flex min-h-screen flex-col justify-center bg-gray-900 py-2">
        <h1 className="text-6xl font-bold">Chats</h1>
        <ul>
          {friends.data?.map((friend) => {
            return <li key={friend.userId}>{friend.userId}</li>;
          })}
        </ul>
      </div>
    </>
  );
};

export default Chats;